import Head from "next/head";
import { useState, useEffect } from "react";
import { GameItem } from "./components/GameItem";
import Loader from "react-loader-spinner";

export default function Home() {
  const [gameIDs, setGameIds] = useState("");
  const [gamesDetails, setGamesDetails] = useState([]);
  useEffect(() => {
    if (gameIDs.length < 1) {
      return;
    }
    async function getGamesDetails() {
      try {
        const response = await fetch(`/api/games-details?ids=${gameIDs}`);
        const data = await response.json();
        const { Products } = data;
        setGamesDetails(Products);
      } catch (err) {
        console.log(err);
      }
    }
    getGamesDetails();
  }, [gameIDs]);
  useEffect(() => {
    async function getGameIDs() {
      try {
        const response = await fetch("/api/games-ids");
        const data = await response.json();
        const removeFirstElement = data.slice(1);
        const ids = removeFirstElement.map((el) => el.id).join(",");
        setGameIds(ids);
      } catch (err) {
        console.log(err);
      }
    }
    getGameIDs();
  }, []);
  return (
    <div className="text-gray-500 dark:text-gray-400 bg-white dark:bg-gray-900 min-h-screen relative">
      <Head>
        <title>XGPG Rated</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-8">
        <header className="flex items-center justify-between">
          <span className="text-white text-m uppercase text-sm tracking-wide">
            Xbox Game Pass games rated
          </span>
          <div>
            <input
              type="search"
              className="rounded-md outline-none p-2 text-sm"
              placeholder="Type name of the game"
            />
          </div>
        </header>
        <div className="mt-6 grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
          {gamesDetails.length > 0 ? (
            gamesDetails.map((el) => (
              <GameItem key={el.ProductId} details={el} />
            ))
          ) : (
            <div className="absolute inset-1/2 translate-y-1/2 translate-x-1/2">
              <Loader type="Circles" color="#00BFFF" height={80} width={80} />
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
